source 'https://rubygems.org'

ruby '>= 3.3.0'

gem 'rails', '~> 7.1'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'administrate', '~> 0.20'
gem 'faraday', '~> 2.9'
gem 'bootsnap', require: false

group :development do
  gem 'web-console'
end
